myui <- fluidPage(
  titlePanel("BodyFat Calculator"),
  hr(),
  uiOutput("Developer1",container = h5),
  uiOutput("Developer2",container = h5),
  uiOutput("Developer3",container = h5),
  hr(),
  ## Code you should write. No unique answer
  textOutput("String",container = h5),
  fluidRow(
    column(3,
           numericInput("Age", label = h3("Age"), value = 23),
           selectInput(inputId = "age", "Unit of Measurement", 
                       choices = c("year"))),
    column(3,
           numericInput("Weight", label = h3("Weight"), value = 154.25),
           selectInput("weight", "Unit of Measurement", 
                       choices = c("lbs", "kg", "g"))),
    column(3,
           numericInput("Height", label = h3("Height"), value = 67.75),
           selectInput("height", "Unit of Measurement", 
                       choices = c("inch", "cm", "m"))),
    column(3,
           numericInput("Adiposity", label = h3("Adiposity"), value = 23.7),
           selectInput("adiposity", "Unit of Measurement", 
                       choices = c("bmi"))),
    column(3,
           numericInput("Chest", label = h3("Chest"), value = 93.1),
           selectInput("chest", "Unit of Measurement", 
                       choices = c("cm","inch"))),
    column(3,
           numericInput("Abdomen", label = h3("Abdomen"), value = 85.2),
           selectInput("abdomen", "Unit of Measurement", 
                       choices = c("cm","inch" ))),
    column(3,
           numericInput("Hip", label = h3("Hip"), value = 94.5),
           selectInput("hip", "Unit of Measurement", 
                       choices = c( "cm","inch"))),
    column(3,
           numericInput("Thigh", label = h3("Thigh"), value = 59),
           selectInput("thigh", "Unit of Measurement", 
                       choices = c("cm","inch"))),
  ),
  hr(),
  fluidRow(
    column(6,
           textOutput("Bodyfat",container=h3),
           verbatimTextOutput("value"))
  ),
  textOutput("Warning",container = h5)
)